config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:index, :show] # for public view
  resources :topics

  get 'welcome/index'

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #

    if user.role? :member
      can :read, :all
      can [:create, :edit, :update, :new], Topic
    end

    if user.role? :admin
      can :manage, :all
    end

    can :read, :all
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/topic_user.rb
class TopicUser < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :set_member

  # has_one :author_page
  has_and_belongs_to_many :topics

  ROLES = %w(member admin)

  def role?(base_role)
    role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
  end

  def set_member
    self.role ||= 'member'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from 'CanCan::AccessDenied' do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
    authorize! :create, Topic, message: 'You need to be signed in to do that.'
  end

  def create
    @topic = current_user.topics.new(topic_params)
    authorize! :create, @topic, message: 'You need to be signed in to do that.'
    if @topic.save
      @topic.users << current_user
      flash[:notice] = 'Topic was saved successfully.'
      redirect_to @topic
    else
      flash[:error] = 'Error creating topic. Please try again.'
      render :new
    end
  end

  def show
    @topic = Topic.find(params[:id])
    authorize! :read, @topic, message: 'You need to be signed in to do that.'
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize! :edit, @topic, message: 'You need to be signed in to do that.'
  end

  def update
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, message: 'You need to be signed in to do that.'
    if @topic.update(topic_params)
      @topic.users << current_user
      redirect_to @topic, notice: 'Topic was successfully updated.'
    else
      render :edit
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # a page showing list of all users/authors, with links to individual author show pages

  def index
    @users = User.all
  end

  # show a page for each user with their name and topics they've written on
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_pages_helper.rb
module AuthorPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuzzphraseWiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
      <li><%= link_to "Authors", users_path %></li>
        <div class="pull-right user-info">
          <% if current_user %>
            Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path %> or
              <%= link_to "Sign Up", new_user_registration_path %>
            <% end %>
          </div>

      </ul>

    <%= yield %>
  </div>
</body>
</html>

app/views/topics/edit.html.erb
<h2> Contribute to Topic: <%= @topic.title %></h2>

<div class="row">
    <div class="col-md-10">
        <%= simple_form_for @topic, :html => {:multipart =>true} do |f| %>

        <%= f.input :body, input_html: { :cols => 100, :rows => 15 }, label: "Apply your edits to this topic" %><br>

        <%= f.button :submit, "Update Topic" %>
        <br><br>
        <% end %>
    </div>
</div>

app/views/topics/index.html.erb
<h2>Index of Topics</h2>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <% @topics.each do |topic| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to topic.title.capitalize, topic %>.
            </h4>
            <small>
              <%= topic.body %>
            </small>

          </div>
        </div><br>
      <% end %>
    </div>
    <div class="col-md-4">
      <% if @user = current_user %>
        <button type="button" class="btn btn-default"><%= link_to "New Topic", new_topic_path %></button>

      <% end %>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<h2>Create a New Topic</h2>

<div class="row">
    <div class="col-md-10">
        <%= simple_form_for @topic, :html => {:multipart =>true} do |f| %>

        <%= f.input :title, label: "Title:" %>
        <br>

        <%= f.input :body, input_html: { :cols => 100, :rows => 15 }, label: "Body:" %><br>

        <%= f.button :submit, "Update Topic" %>
        <br><br>
        <% end %>
    </div>
</div>

app/views/topics/show.html.erb
<h2>Topic: <%= @topic.title %></h2>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <p><%= @topic.body %></p>
    </div>
    <div class="col-md-4">

        <button type="button" class="btn btn-default"><%= link_to "Back to Index", topics_path %></button>
        <% if current_user %>
        <button type="button" class="btn btn-default"><%= link_to "Edit Topic", edit_topic_path %></button>
        <% end %>


      <br><br>
      <h4>List of Contributors:</h4>
        <ul>
          <% @topic.users.each do |user| %>
          <li>
            <%= link_to user.email, user_path(@topic) %>
          </li>
          <% end %>
        </ul>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<h2>Index of Authors</h2>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <% @users.each do |user| %>
        <p class="media-heading">
          <%= link_to user.email, user %>
        </p>
      <% end %>
    </div>
  </dvi>
</div>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<h3><%= @user.email %></h3>

<ul>
  <% @user.topics.each do |topic| %>
    <li>
      <%= link_to topic.title, topic_path(@user.topic) %>
    </li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<div class="hero-unit">
  <h1>BuzzPhrase Wiki</h1>
  <p>BuzzPhrase Wiki is a place to share, discuss, and generally make fun of business buzzwords!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary btn-large' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-large' %> today!
  </p>
</div>

<!-- <div class="row">
  <div class="span4">
    <h2>Amazing Point 1</h2>
    <p>This is some content about how great point 1 is. You should really use Bloccit because of it! No seriously, it really is amazing and great and you should really check it out.</p>
  </div>
  <div class="span4">
    <h2>Amazing Point 2</h2>
    <p>This is some content about how great point 2 is. You should really use Bloccit because of it! No seriously, it really is amazing and great and you should really check it out.</p>
  </div>
  <div class="span4">
    <h2>Amazing Point 3</h2>
    <p>This is some content about how great point 3 is. You should really use Bloccit because of it! No seriously, it really is amazing and great and you should really check it out.</p>
  </div>
</div>
 -->